services:
  backend:
    container_name: shopper-backend
    image: shopper-backend:1.0.0
    build:
      context: ./backend/user/
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:3001"
    volumes:
      - ./backend/user/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GOOGLE_API_KEY=$(GOOGLE_API_KEY)
      - DATABASE_URL=postgresql://postgres:password@shopper-postgres:5432/shopperdb
    depends_on:
      - shopper-postgres
    networks:
      - app_network

  # frontend:
  #   image: shopper-frontend:1.0.0
  #   build:
  #     context: ./frontend/user/
  #     dockerfile: .docker/Dockerfile
  #   ports:
  #     - "80:5173"
  #   volumes:
  #     - ./frontend/user:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV: development
  #     - BACKEND_URL: http://localhost:8080/
  #   depends_on:
  #       - shopper-backend

  shopper-postgres:
    image: postgres:15
    container_name: shopper-postgres
    environment:
      - POSTGRES_DB=shopperdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge