export enum ErrorCodes {
  INVALID_DATA = "INVALID_DATA",
  INVALID_DRIVER = "INVALID_DRIVER",
  NO_RIDES_FOUND = "NO_RIDES_FOUND",
  INVALID_DISTANCE = "INVALID_DISTANCE",
  DRIVER_NOT_FOUND = "DRIVER_NOT_FOUND",
}
